### ISSUE TITLE
googleCTF2020/echoserver

### ISSUE THREAD

**Issue by Kyle-Kyle** [perfectblue/ctf-writeups#10]
I read your solution and I see the commented code "sending 64 connections" through 64 different threads. In my understanding, this should hurt stability a lot. I just wonder how unstable it was compared with "sending 64 connections sequentially in one thread".

@stong

**Comment by Kyle-Kyle** [comment]
And there is a bug in the `erase` code so every time I close/shutdown a fd, the server just crashes. How did you manage to call close/shutdown on the fds and still make it not crash?

**Comment by stong** [comment]
I will ask @VoidMercy

**Comment by VoidMercy** [comment]
On remote, I experienced similar instability with both 64 threads, and 1 thread. However, the 1 thread exploit was easier to write since the fds end up being sequential, so I stuck with that.

I used shutdown on the fds in reverse order in which the fds were created, with sleeps in between each shutdown call.

**Comment by Kyle-Kyle** [comment]
@VoidMercy That makes sense. Thanks!
