### ISSUE TITLE
question about machbookair from balson ctf 2020

### ISSUE THREAD

**Issue by Kyle-Kyle** [perfectblue/ctf-writeups#12]
1. How did you managed to leak both canary and pie address in one run within 90s?, for me, leaking canary takes about 60s and I ran my script from a server located in singapore.
My solution leaks canary only and uses libsystem addresses for ROPing. I can confirm that the canary is correct but somehow it keeps crashing at my ROP chain remotely. (It works locally)
2. Do you have any idea why this happen? my local machine is 10.15.7

**Comment by sampritipanda** [comment]
> How did you managed to leak both canary and pie address in one run within 90s?, for me, leaking canary takes about 60s and I ran my script from a server located in singapore.

GCP Instance in Taiwan, under 1 ms ping :stuck_out_tongue: 

> My solution leaks canary only and uses libsystem addresses for ROPing. I can confirm that the canary is correct but somehow it keeps crashing at my ROP chain remotely. (It works locally)

Not sure about this one, once we leaked PIE/lib addresses, ROP worked perfectly. I know I had some issues with sending input too fast, which is why everything is `sendlineafter`.

These are the libraries on my Mac:

```
b9b3d177249279ae77f62b1c0e993849  libsystem_c.dylib
d9f080353f8098cce1d0cafcf97a15d3  libsystem_platform.dylib
```

We used libsystem_platform (leak using strcmp I believe) since we had issues with gadgets from libsystem_c.

**Comment by Kyle-Kyle** [comment]
Now I know GCE has instances in Taiwan, it may be helpful for coming HITCON. Thanks!!
